name = "STMOZOO"
uuid = "8e7dc78f-7190-4116-bf88-3d148ae9f088"
authors = ["michielstock <michielfmstock@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
