name = "STMOZOO"
uuid = "8e7dc78f-7190-4116-bf88-3d148ae9f088"
authors = ["michielstock <michielfmstock@gmail.com>"]
version = "0.1.0"

[deps]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ExprOptimization = "0d84ce59-e78b-5c9a-b954-3a5400d7f6ed"
ExprRules = "e7058ba0-a568-556c-b31a-209ee9d855a8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TreeView = "39424ebd-4cf3-5550-a685-96706a953f40"
